apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    events {
      worker_connections  10240;
    }
    http {
      server {
      listen 80;
      listen [::]:80;

      server_name api.test;
      root /var/www/api;
      index index.html;

      location / {
            proxy_pass http://10.52.198.102:9000;
            rewrite /(.*) /$1 break;
            proxy_set_header    Host $host;
            proxy_set_header    X-Real-IP $remote_addr;
            proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header    X-Forwarded-Proto $scheme;
            proxy_read_timeout 100;
            proxy_send_timeout 100;
            proxy_connect_timeout 100;
            client_max_body_size 20M;
        }
      }
    }
