apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hosts
spec:
  rules:
    - host: http://35.223.153.169.nip.io/
      http:
        paths: 
          - backend:
              serviceName: nginx-loadbalancing
              servicePort: 80
