---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-autoscaling
  labels:
    app: tomcat
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      project: tomcat
  template:
    metadata:
      labels:
        project: tomcat
      containers:
        - name: tomcat
          image: us-central1-docker.pkg.dev/seismic-vista-405108/diplom/tomcat
          ports:
            - containerPort: 8888
nodeSelector:
  team: backend
