---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      project: tomcat
  template:
    metadata:
      labels:
        project: tomcat
      containers:
      - name: tomcat
        image: us-central1-docker.pkg.dev/seismic-vista-405108/diplom/tomcat:46
        ports:
            - containerPort: 9000
nodeSelector:
  team: backend
