apiVersion: v1
kind: Service
metadata:
  name: web-backend-loadbalancing
  labels:
    env: prod
spec:
  selector:
    app: web-backend
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 443
  type: ClusterIP