apiVersion: v1
kind: Service
metadata:
  name: web-backend-loadbalancing
  labels:
    env: prod
spec:
  selector:
    app: tomcat
  ports:
  - port: 9000
    protocol: TCP
    targetPort: http-tomcat